name: update publications workflow
on:
  schedule:
    - cron: "0 9 * * 5" # every friday @ 9am
  workflow_dispatch:
jobs:
  update-publications-via-pubmed-api:
    name: update GoNL publication list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [4.0.3]
    steps:
      - uses: actions/checkout@v2

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: $({ matrix.r-version })

      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c(
            "dplyr", "httr", "rjson", "cli",
            "purrr", "tibble", "rlist", "htmltools"
          ))
        shell: Rscript {0}

      - name: Run PubMed API
        run: |
          source("R/pubmed_02_update.R")
        shell: Rscript {0}
